services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    command: mix run --no-halt
    volumes:
      - ./backend:/app:delegated
      - backend_deps:/app/deps
      - backend_build:/app/_build

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000  
    depends_on:
      - backend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules

volumes:    
  backend_deps:
  backend_build:
  frontend_node_modules:
